# frozen_string_literal: true

require_relative "fiscalrail/version"
require_relative "fiscalrail/errors"
require_relative "fiscalrail/model"
require_relative "fiscalrail/serialization"
require_relative "fiscalrail/generated/contract"
require_relative "fiscalrail/generated/models"
require_relative "fiscalrail/decoder"
require_relative "fiscalrail/binary_content"
require_relative "fiscalrail/transport"
require_relative "fiscalrail/resource"
require_relative "fiscalrail/resources/accounts"
require_relative "fiscalrail/resources/api_keys"
require_relative "fiscalrail/resources/customers"
require_relative "fiscalrail/resources/event_destinations"
require_relative "fiscalrail/resources/events"
require_relative "fiscalrail/resources/invoice_series"
require_relative "fiscalrail/resources/invoices"
require_relative "fiscalrail/resources/invoice_pdfs"
require_relative "fiscalrail/resources/payment_instructions"
require_relative "fiscalrail/resources/tax_regimes"
require_relative "fiscalrail/client"
require_relative "fiscalrail/tax_regimes/es"
require_relative "fiscalrail/webhooks"
